# Generated by Django 4.0.4 on 2022-06-19 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('idColor', models.AutoField(primary_key=True, serialize=False)),
                ('nombreColor', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False)),
                ('nomRol', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('idTipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTipo', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=30)),
                ('foto', models.ImageField(blank='', default='foto_perfil/foto_perfil_default.png', upload_to='foto_perfil')),
                ('contrasena', models.CharField(max_length=20)),
                ('RolUsuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Core.rolusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=60)),
                ('fotoProducto', models.ImageField(blank='', upload_to='foto_producto')),
                ('precio', models.IntegerField(default=0)),
                ('detalle', models.CharField(max_length=60)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.categoria')),
                ('Color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.color')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='TipoProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.tipoproducto'),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idCarrito', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField(default=1)),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.producto')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.usuario')),
            ],
        ),
    ]
