# Generated by Django 4.0.4 on 2022-06-13 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False)),
                ('nomRol', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=30)),
                ('foto', models.ImageField(blank='', default='foto_perfil/foto_perfil_default.png', upload_to='foto_perfil')),
                ('contrasena', models.CharField(max_length=20)),
                ('RolUsuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Core.rolusuario')),
            ],
        ),
    ]
