# Generated by Django 4.0.4 on 2022-06-18 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('idColor', models.AutoField(primary_key=True, serialize=False)),
                ('nombreColor', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('idTipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTipo', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=60)),
                ('fotoProducto', models.ImageField(blank='', default='foto_perfil/foto_perfil_default.png', upload_to='foto_perfil')),
                ('detalle', models.CharField(max_length=60)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.categoria')),
                ('Color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.color')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='TipoProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.tipoproducto'),
        ),
    ]
