# Generated by Django 4.0.4 on 2022-06-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_categoria_color_tipoproducto_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fotoProducto',
            field=models.ImageField(blank='', upload_to='foto_producto'),
        ),
    ]
