# Generated by Django 4.0.4 on 2022-06-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_remove_carrito_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(default='123 Sesame Street', max_length=50),
        ),
    ]
