# Generated by Django 4.0.4 on 2022-06-22 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_usuario_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('IdVenta', models.AutoField(primary_key=True, serialize=False)),
                ('NumVenta', models.IntegerField(default=0)),
                ('Precio', models.IntegerField(default=0)),
                ('Fecha', models.DateField(auto_now_add=True)),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.producto')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.usuario')),
            ],
        ),
    ]
