# Generated by Django 4.0.4 on 2022-06-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('IdArriendo', models.AutoField(primary_key=True, serialize=False)),
                ('FechaArriendo', models.DateField()),
                ('FechaDevolucion', models.DateField()),
                ('CategoriaBicicleta', models.CharField(max_length=60)),
                ('RutArrendador', models.CharField(max_length=60)),
            ],
        ),
    ]
